# Generated by Django 2.0.4 on 2018-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_dir',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
