# Generated by Django 2.0.4 on 2018-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20180413_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
