# Generated by Django 2.0.4 on 2018-04-14 20:38

from django.db import migrations


def copy_animer_dir(apps, schema_editor):
		Anime = apps.get_model('anime', 'Anime')
		for anime in Anime.objects.all():
			anime.anime_slug = anime.anime_dir
			anime.save()

class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_slug'),
    ]

    operations = [
    	migrations.RunPython(copy_animer_dir),
    ]
