# Generated by Django 2.0.4 on 2018-04-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20180414_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_dir',
        ),
    ]
