# Generated by Django 2.0.4 on 2018-04-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_auto_20180414_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_studio', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='premiere',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='anime.Premiere'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(to='anime.Studio'),
        ),
    ]
