# Generated by Django 2.0.4 on 2018-04-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20180419_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_slug', models.SlugField()),
                ('movie_type', models.CharField(max_length=10)),
                ('movie_cover', models.ImageField(upload_to='images/')),
                ('movie_publication_date', models.DateTimeField(blank=True, null=True)),
                ('movie_count', models.PositiveIntegerField(default=0)),
                ('genres', models.ManyToManyField(to='anime.Genre')),
                ('premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Premiere')),
                ('studio', models.ManyToManyField(to='anime.Studio')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
