# Generated by Django 2.0.4 on 2018-04-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_episode_episode_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodeurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('video_url', models.CharField(max_length=250)),
                ('video_quality', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Movieurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('video_url', models.CharField(max_length=250)),
                ('video_quality', models.PositiveIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Episode')),
            ],
        ),
    ]
